name: workflowrun
on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(context);
            console.log("Head repo");
            console.log(context.payload.workflow_run.head_repository);
            console.log("repo");
            console.log(context.payload.workflow_run.repository);
